fix code by check
WorksApplications/elasticsearch-chikkar pull request #4
Opened 2019-06-25 03:46 UTC by liu-to

2019-06-26 07:21 UTC, kazuma-t requested changes

2019-06-26 07:21 UTC, kazuma-t commented on src/main/java/com/worksap/nlp/elasticsearch/plugins/chikkar/DictionaryManager.java
> +            log.error(e.getMessage());
In this case, the user cannot know an error is happen. It is better to throw an exception, isn't it?

2019-06-26 07:57 UTC, kazuma-t approved these changes

2019-06-26 10:42 UTC, liu-to commented on src/main/java/com/worksap/nlp/elasticsearch/plugins/chikkar/DictionaryManager.java
> +            log.error(e.getMessage());
Yes, you are right. Modified.

2019-06-27 01:01 UTC, kazuma-t requested changes

2019-06-27 01:01 UTC, kazuma-t commented on src/test/java/com/worksap/nlp/elasticsearch/plugins/chikkar/ChikkarTest.java
> +        FileOutputStream fileOut = new FileOutputStream(binPath.toFile());
Use try-with-resources statements

2019-06-27 02:08 UTC, liu-to commented on src/test/java/com/worksap/nlp/elasticsearch/plugins/chikkar/ChikkarTest.java
> +        FileOutputStream fileOut = new FileOutputStream(binPath.toFile());
OK, modified.

2019-06-27 03:03 UTC, kazuma-t approved these changes

2019-06-27 03:03 UTC, merged